apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp-pod
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28
      command: ["sh", "-c", "echo The app is running! && sleep 3600"]
      env:
        - name: FIRSTNAME
          value: "Piyush"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: ["sh", "-c"] #command to run
      args:
        [
          "until nslookup myservice.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done",
        ]
      resources:
        requests:
          memory: "32Mi"
          cpu: "50m"
        limits:
          memory: "64Mi"
          cpu: "100m"
